services:
  node:
    container_name: ${DOCKER_PROJECT_NAME}_node
    image: node:18-alpha3.18
    volumes:
      - ./:var/www/html
    working_dir: /var/www/html
    command: /bin/sh -c "npm install && npm run build"
